config/routes.rb
Rails.application.routes.draw do
  root 'lines#index'
  namespace :productions do
    resources :searches, only: :index do
      collection do
        get 'search'
      end
    end
  end

  resources :lines do
    resources :productions
  end
end

app/models/production.rb
class Production < ApplicationRecord
  belongs_to :product
  belongs_to :line

  validates :date, presence: true
  validates :product_id, presence: true

  def self.search(date,line_id,product_id)
    Production.find_by("(date = ?) AND (line_id = ?) AND (product_id = ?)",
                 date, line_id,  product_id)
  end
end

app/controllers/productions/searches_controller.rb
class Productions::SearchesController < ApplicationController
  def index
    @production = Production.new
  end

  def search
    product_id = Product.find_by(code: params[:production][:product_id]).id
    @production_result = Production.search(params[:production][:date], params[:production][:line_id], product_id)

    gon.date = ["7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", 
                "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", 
                "23:00", "0:00", "1:00", "2:00", "3:00", "4:00", "5:00", "6:00"]

  begin_boxs = [@production_result.begin_box1,@production_result.begin_box2,@production_result.begin_box3,
                @production_result.begin_box4,@production_result.begin_box5,@production_result.begin_box6,
                @production_result.begin_box7,@production_result.begin_box8,@production_result.begin_box9,
                @production_result.begin_box10,@production_result.begin_box11,@production_result.begin_box12,
                @production_result.begin_box13,@production_result.begin_box14,@production_result.begin_box15,
                @production_result.begin_box16,@production_result.begin_box17,@production_result.begin_box18,
                @production_result.begin_box19,@production_result.begin_box20,@production_result.begin_box21,
                @production_result.begin_box22,@production_result.begin_box23,@production_result.begin_box24]
  end_boxs = [@production_result.end_box1,@production_result.end_box2,@production_result.end_box3,
              @production_result.end_box4,@production_result.end_box5,@production_result.end_box6,
              @production_result.end_box7,@production_result.end_box8,@production_result.end_box9,
              @production_result.end_box10,@production_result.end_box11,@production_result.end_box12,
              @production_result.end_box13,@production_result.end_box14,@production_result.end_box15,
              @production_result.end_box16,@production_result.end_box17,@production_result.end_box18,
              @production_result.end_box19,@production_result.end_box20,@production_result.end_box21,
              @production_result.end_box22,@production_result.end_box23,@production_result.end_box24]

    #No.1の箱までのnilの数
    begin_box_index = begin_boxs.index(1)

    #nilの除去
    begin_boxs_compact = begin_boxs.compact
    end_boxs_compact = end_boxs.compact

    #入れ目の取得
    per_case = @production_result.product.per_case

    #一時間あたりのできた箱数の計算
    #まずは差分を取る
    @boxs_difference = []
    end_boxs_compact.zip(begin_boxs_compact).each do |end_box, begin_box|
      box_difference = end_box - begin_box
      @boxs_difference.push(box_difference)
    end
    
    #差分が0のときはそのまま、0以外の時はプラス1をする。プラス1をしないと、正確な一時間にできた箱数にならない
    boxs_difference_plus = @boxs_difference.map do |i|
      if i != 0
        i = i + 1
      else
        i
      end
    end

    #一時間ごとの生産数(実数)
    @day_productions = []
    boxs_difference_plus.each do |b|
      number = b * per_case
      @day_productions.push(number)
    end

    #累計の計算(day_cumulative_productions=一時間ごとの生産数の累計)
    @day_cumulative_productions = @day_productions.size.times.map{|i| @day_productions[0..i].inject(:+)}

    #配列の先頭にnilを追加
    begin_box_index.times do |i|
      @day_productions.unshift(nil)
    end

    begin_box_index.times do |i|
      @day_cumulative_productions.unshift(nil)
    end

    #グラフに反映するために、gonに格納
    gon.day_productions = @day_productions
    gon.day_cumulative_productions = @day_cumulative_productions
    gon.result_date = @production_result.date.strftime("%Y年%m月%d日")
  end
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  include ApplicationHelper
  before_action :set_line

  def index
    gon.date = ["7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", 
                "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", 
                "23:00", "0:00", "1:00", "2:00", "3:00", "4:00", "5:00", "6:00"]
    gon.production = [nil]
    gon.cumulative_production = [nil]
    gon.prediction = [nil]

    @production = Production.new
  end

  def new
    
  end

  def create
    product_id = Product.find_by(code: params[:production][:product_id]).id
    production_page = Production.create(production_params.merge(product_id: product_id))

    redirect_to edit_line_production_path(line_id: production_page.line_id, id:production_page.id)
  end

  def edit
    @production = Production.find(params[:id])
    gon.date = ["7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", 
                "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", 
                "23:00", "0:00", "1:00", "2:00", "3:00", "4:00", "5:00", "6:00"]

    begin_boxs = [@production.begin_box1,@production.begin_box2,@production.begin_box3,
                  @production.begin_box4,@production.begin_box5,@production.begin_box6,
                  @production.begin_box7,@production.begin_box8,@production.begin_box9,
                  @production.begin_box10,@production.begin_box11,@production.begin_box12,
                  @production.begin_box13,@production.begin_box14,@production.begin_box15,
                  @production.begin_box16,@production.begin_box17,@production.begin_box18,
                  @production.begin_box19,@production.begin_box20,@production.begin_box21,
                  @production.begin_box22,@production.begin_box23,@production.begin_box24]
    end_boxs = [@production.end_box1,@production.end_box2,@production.end_box3,
                @production.end_box4,@production.end_box5,@production.end_box6,
                @production.end_box7,@production.end_box8,@production.end_box9,
                @production.end_box10,@production.end_box11,@production.end_box12,
                @production.end_box13,@production.end_box14,@production.end_box15,
                @production.end_box16,@production.end_box17,@production.end_box18,
                @production.end_box19,@production.end_box20,@production.end_box21,
                @production.end_box22,@production.end_box23,@production.end_box24]
    
    #No.1の箱までのnilの数
    begin_box_index = begin_boxs.index(1)

    #nilの除去
    begin_boxs_compact = begin_boxs.compact
    end_boxs_compact = end_boxs.compact

    #入れ目の取得
    per_case = @production.product.per_case

    #一時間あたりのできた箱数の計算
    #まずは差分を取る
    @boxs_difference = []
    end_boxs_compact.zip(begin_boxs_compact).each do |end_box, begin_box|
      box_difference = end_box - begin_box
      @boxs_difference.push(box_difference)
    end
    
    #差分が0のときはそのまま、0以外の時はプラス1をする。プラス1をしないと、正確な一時間にできた箱数にならない
    boxs_difference_plus = @boxs_difference.map do |i|
      if i != 0
        i = i + 1
      else
        i
      end
    end

    #下で.sizeメソッドを使うための準備
    per_boxs_cal = boxs_difference_plus

    #一時間ごとの生産数(実数)
    @day_productions = []
    boxs_difference_plus.each do |b|
      number = b * per_case
      @day_productions.push(number)
    end

    #単回帰用に準備
    day_productions_cal = @day_productions
    
    #累計の計算(day_cumulative_productions=一時間ごとの生産数の累計)
    @day_cumulative_productions = @day_productions.size.times.map{|i| @day_productions[0..i].inject(:+)}

    #配列の先頭にnilを追加
    begin_box_index.times do |i|
      @day_productions.unshift(nil)
    end

    begin_box_index.times do |i|
      @day_cumulative_productions.unshift(nil)
    end

    #グラフに反映するために、gonに格納
    gon.day_productions = @day_productions
    gon.day_cumulative_productions = @day_cumulative_productions


    # 単回帰分析
    # 横軸xのための配列の用意
    xs = []
    per_boxs_cal.size.times.map do |x|
      xs.push(x)
      x = x + 1
    end

    #累計の算出
    per_boxs_cumulative = per_boxs_cal.size.times.map{|i| per_boxs_cal[0..i].inject(:+)}

    if per_boxs_cal.size > 1
      ys = per_boxs_cumulative

      #xとyの平均値を求める
      x_mean = xs.inject(:+) / xs.length
      y_mean = ys.inject(:+) / ys.length

      #中心化
      @xcs = []
      @ycs = []

      xs.each do |x|
        xc = x - x_mean
        @xcs.push(xc)
      end

      ys.each do |y|
        yc = y - y_mean
        @ycs.push(yc)
      end
      
      #要素積
      @xxs = []
      @xys = []

      @xcs.zip(@xcs).each do |xc_1, xc_2|
        xx = xc_1 * xc_2
        @xxs.push(xx)
      end

      @xcs.zip(@ycs).each do |xc, yc|
        xy = xc * yc
        @xys.push(xy)
      end

      # パラメータの決定
      a = @xys.sum/@xxs.sum
      #パラメータの四捨五入(aが少数になると、予測する生産数が少数になるため)
      a = a.round
    else
      a = per_boxs_cal[0] + 1
    end
    
    #先頭の空白の部分を除いた分だけ、パラメータaが入った配列を用意する
    parameters = []
    (24 - begin_box_index).times.map do |es|
      parameters.push(a)
    end

    #パラメータが入った配列に入れ目をかける
    @parameters_per_case = []
    parameters.each do |parameter|
      parameter_per_case = parameter * per_case
      @parameters_per_case.push(parameter_per_case)
    end
    
    #累計を計算する計算
    parameters_per_case_cumulative = @parameters_per_case.size.times.map{|i| @parameters_per_case[0..i].inject(:+)}
    #先頭の空白の分だけnilを配列の先頭に加える
    if begin_box_index == 0
      @productions_predict = parameters_per_case_cumulative
    else
      begin_box_index.times do |i|
        @productions_predict = parameters_per_case_cumulative.unshift(nil)
      end
    end
    #単回帰モデルの完成(productions_predict)
    gon.productions_predict = @productions_predict

    #縦軸の目盛間隔を入れ目と同じにするための準備
    gon.per_case = per_case

    @begin_box_index = begin_box_index
  end

  def update
    @production = Production.find(params[:id])
    if @production.update(production_params)
      redirect_to edit_line_production_path(line_id: @production.line_id, id: @production.id), notice: '更新しました'
    else
      render :edit
    end
  end
  
  def destroy
  end

  def show
  end

  private
  def production_params
    params.require(:production).permit(:date,
                                        :begin_box1, :begin_box2, :begin_box3, :begin_box4, :begin_box5, :begin_box6, :begin_box7, :begin_box8,  
                                        :begin_box9, :begin_box10, :begin_box11, :begin_box12, :begin_box13, :begin_box14, :begin_box15,:begin_box16, 
                                        :begin_box17, :begin_box18, :begin_box19, :begin_box20, :begin_box21, :begin_box22, :begin_box23, :begin_box24,
                                        :end_box1, :end_box2, :end_box3, :end_box4, :end_box5, :end_box6, :end_box7, :end_box8,
                                        :end_box9, :end_box10, :end_box11, :end_box12, :end_box13, :end_box14, :end_box15, :end_box16,
                                        :end_box17, :end_box18, :end_box19, :end_box20, :end_box21, :end_box22, :end_box23, :end_box24)
                                        .merge(line_id: params[:line_id])
  end

  def set_line
    @line = Line.find(params[:line_id])
  end
end

app/helpers/productions/searches_helper.rb
module Productions::SearchesHelper
end

app/helpers/productions_helper.rb
module ProductionsHelper
  def cs(as, bs)
    @merge = []
    as.zip(bs).each do |a, b|
      @merge.push(a)
      @merge.push(b)
    end
  end
  
  def judgment(as, bs)
    merge = []
    as.zip(bs).each do |a, b|
      merge.push(a)
      merge.push(b)
    end

    merge_length = merge.length / 2
    (0..merge_length).each do |i|
      if cs[i] >= cs[i + 1]
        puts "nooooooo"
        break
      end
    end
  end
end

app/views/productions/_graph.html.haml
.main
  %canvas#myChart{height: "450", width: "900"}
  :javascript
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: gon.date,
        datasets: [{
          label: "累計生産数",
          data: gon.cumulative_production,
          type: 'line',
          yAxisID: "y-axis-2",
          fill: false,
          borderColor: 'rgba(52, 147, 255, 1.0)',
        },{
          label: "予想",
          data: gon.prediction,
          type: 'line',
          fill: false,
          yAxisID: "y-axis-2",
           borderColor: 'rgba(125, 215, 135, 1.0)',
        },{
          label: "生産数",
          data: gon.production,
          backgroundColor: 'rgba(255, 99, 132, 1.0)',
          borderColor: 'rgba(255, 50, 132, 1.0)',
          fill: false,
          categoryPercentage: 1,
          yAxisID: "y-axis-1",
        }]
      },
      options: {
        title:  {
          display: true,
          text: "今日の生産数"
        },
        scales: {
          xAxes:[{
            categoryPercentage: 1,
          }],
          yAxes: [{
            id: "y-axis-1",
            type: "linear",
            position: "left",
            scaleLabel: {
              display: true,
              labelString: "一時間当たりの生産数",
              fontSize: 14,
              fontColor: 'rgba(255, 99, 132, 1.0)'
            },
            ticks: {
              beginAtZero:true
            }
          },{
            id: "y-axis-2",
            type: "linear",
            position: "right",
            scaleLabel: {
              display: true,
              labelString: "累計生産数",
              fontSize: 14,
              fontColor: 'rgba(52, 147, 255, 1.0)'
            },
            ticks: {
              beginAtZero:true
            }
          }]
        }
      }
    });

app/views/productions/_table.html.haml
.tables
  %table.table
    %thead
      %tr
        %th 時間
      %tr
        %td 7:00~8:00
      %tr
        %td 8:00~9:00
      %tr
        %td 9:00~10:00
      %tr
        %td 11:00~12:00
      %tr
        %td 13:00~14:00
      %tr
        %td 14:00~15:00
      %tr
        %td 15:00~16:00
      %tr
        %td 16:00~17:00
      %tr
        %td 18:00~19:00
      %tr
        %td 19:00~20:00
      %tr
        %td 20:00~21:00
      %tr
        %td 21:00~22:00
      %tr
        %td 22:00~23:00
      %tr
        %td 23:00~00:00
      %tr
        %td 00:00~01:00
      %tr
        %td 01:00~02:00
      %tr
        %td 02:00~03:00
      %tr
        %td 03:00~04:00
      %tr
        %td 04:00~05:00
      %tr
        %td 05:00~06:00
      %tr
        %td 06:00~07:00
    

  %table.table
    %thead
      %tr
        %th 実数
        %th 累計
        %th タスクの内容
        %th 箱_begin
        %th ~
        %th 箱_end

  %table.table
    %thead
      %tr
        %th テスト
      %tr
        %td 実数

  = form_for [@begin_box], url: line_productions_path do |f|
    = f.text_field :begin_box07
    = f.text_field :begin_box08
    = f.text_field :begin_box09
    = f.submit 'Send', class: 'main__form__send-btn'

app/views/productions/edit.html.haml
= form_for [@production],url: line_production_path do |f|
  .index 
    .form
      .form__info 
        .form__info__date
          = f.date_field :date
        .form__info__post
          = f.submit '更新', class: "form__info__post__btn"
      .form__table
        %table.table
          %thead
            %tr
              %th 時間
              %th 実数
              %th 累計
              %th 箱
              %th 番
              %th 号
            %tr
              %td 7:00~8:00
              %td 
                = @day_productions[0]
              %td 
                = @day_cumulative_productions[0]
              %td.input_area
                = f.text_field :begin_box1, class: "input_number"
              %td〜
              %td.input_area
                = f.text_field :end_box1, class: "input_number"
            %tr
              %td 8:00~9:00
              %td 
                = @day_productions[1]
              %td 
                = @day_cumulative_productions[1]
              %td.input_area
                = f.text_field :begin_box2, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box2, class: "input_number"
            %tr
              %td 9:00~10:00
              %td 
                = @day_productions[2]
              %td 
                = @day_cumulative_productions[2]
              %td.input_area
                = f.text_field :begin_box3, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box3, class: "input_number"
            %tr
              %td 10:00~11:00
              %td 
                = @day_productions[3]
              %td 
                = @day_cumulative_productions[3]
              %td.input_area
                = f.text_field :begin_box4, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box4, class: "input_number"
            %tr
              %td 11:00~12:00
              %td 
                = @day_productions[4]
              %td 
                = @day_cumulative_productions[4]
              %td.input_area
                = f.text_field :begin_box5, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box5, class: "input_number"
            %tr
              %td 12:00~13:00
              %td 
                = @day_productions[5]
              %td 
                = @day_cumulative_productions[5]
              %td.input_area
                = f.text_field :begin_box6, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box6, class: "input_number"
            %tr
              %td 13:00~14:00
              %td 
                = @day_productions[6]
              %td 
                = @day_cumulative_productions[6]
              %td.input_area
                = f.text_field :begin_box7, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box7, class: "input_number"
            %tr
              %td 14:00~15:00
              %td 
                = @day_productions[7]
              %td 
                = @day_cumulative_productions[7] 
              %td.input_area
                = f.text_field :begin_box8, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box8, class: "input_number"
            %tr
              %td 15:00~16:00
              %td 
                = @day_productions[8]
              %td 
                = @day_cumulative_productions[8]
              %td.input_area
                = f.text_field :begin_box9, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box9, class: "input_number"
            %tr
              %td 16:00~17:00
              %td 
                = @day_productions[9]
              %td 
                = @day_cumulative_productions[9] 
              %td.input_area
                = f.text_field :begin_box10, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box10, class: "input_number"
            %tr
              %td 17:00~18:00
              %td 
                = @day_productions[10]
              %td 
                = @day_cumulative_productions[10] 
              %td.input_area
                = f.text_field :begin_box11, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box11, class: "input_number"
            %tr
              %td 18:00~19:00
              %td 
                = @day_productions[11]
              %td 
                = @day_cumulative_productions[11] 
              %td.input_area
                = f.text_field :begin_box12, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box12, class: "input_number"
            %tr
              %td 19:00~20:00
              %td 
                = @day_productions[12]
              %td 
                = @day_cumulative_productions[12] 
              %td.input_area
                = f.text_field :begin_box13, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box13, class: "input_number"
            %tr
              %td 20:00~21:00
              %td 
                = @day_productions[13]
              %td 
                = @day_cumulative_productions[13] 
              %td.input_area
                = f.text_field :begin_box14, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box14, class: "input_number"
            %tr
              %td 21:00~22:00
              %td 
                = @day_productions[14]
              %td 
                = @day_cumulative_productions[14] 
              %td.input_area
                = f.text_field :begin_box15, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box15, class: "input_number"
            %tr
              %td 22:00~23:00
              %td 
                = @day_productions[15]
              %td 
                = @day_cumulative_productions[15] 
              %td.input_area
                = f.text_field :begin_box16, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box16, class: "input_number"
            %tr
              %td 23:00~00:00
              %td 
                = @day_productions[16]
              %td 
                = @day_cumulative_productions[16] 
              %td.input_area
                = f.text_field :begin_box17, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box17, class: "input_number"
            %tr
              %td 00:00~01:00
              %td 
                = @day_productions[17]
              %td 
                = @day_cumulative_productions[17] 
              %td.input_area
                = f.text_field :begin_box18, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box18, class: "input_number"
            %tr
              %td 01:00~02:00
              %td 
                = @day_productions[18]
              %td 
                = @day_cumulative_productions[18] 
              %td.input_area
                = f.text_field :begin_box19, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box19, class: "input_number"
            %tr
              %td 02:00~03:00
              %td 
                = @day_productions[19]
              %td 
                = @day_cumulative_productions[19] 
              %td.input_area
                = f.text_field :begin_box20, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box20, class: "input_number"
            %tr
              %td 03:00~04:00
              %td 
                = @day_productions[20]
              %td 
                = @day_cumulative_productions[20] 
              %td.input_area
                = f.text_field :begin_box21, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box21, class: "input_number"
            %tr
              %td 04:00~05:00
              %td 
                = @day_productions[21]
              %td 
                = @day_cumulative_productions[21] 
              %td.input_area
                = f.text_field :begin_box22, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box22, class: "input_number"
            %tr
              %td 05:00~06:00
              %td 
                = @day_productions[22]
              %td 
                = @day_cumulative_productions[22] 
              %td.input_area
                = f.text_field :begin_box23, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box23, class: "input_number"
            %tr
              %td 06:00~07:00
              %td 
                = @day_productions[23]
              %td 
                = @day_cumulative_productions[23] 
              %td.input_area
                = f.text_field :begin_box24, class: "input_number"
              %td
              %td.input_area
                = f.text_field :end_box24, class: "input_number"
    .main 
      .main__product
        .main__product__line
          .main__product__line__name
            = @line.name
          .main__product__info__perbox
            = @production.product.per_case
            本
        .main__product__info
          .main__product__info__code
            = @production.product.code
          .main__product__info__name
            = @production.product.name
      .main__graph
        .main__graph__image
          %canvas#myChart{height: "430", width: "800"}
          :javascript
            var ctx = document.getElementById("myChart").getContext('2d');
            var myChart = new Chart(ctx, {
              type: 'bar',
              data: {
                labels: gon.date,
                datasets: [{
                  label: "累計生産数",
                  data: gon.day_cumulative_productions,
                  type: 'line',
                  yAxisID: "y-axis-2",
                  fill: false,
                  borderColor: 'rgba(52, 147, 255, 1.0)',
                },{
                  label: "予想",
                  data: gon.productions_predict,
                  type: 'line',
                  fill: false,
                  yAxisID: "y-axis-2",
                  borderColor: 'rgba(125, 215, 135, 1.0)',
                },{
                  label: "生産数",
                  data: gon.day_productions,
                  backgroundColor: 'rgba(255, 99, 132, 1.0)',
                  borderColor: 'rgba(255, 50, 132, 1.0)',
                  fill: false,
                  categoryPercentage: 1,
                  yAxisID: "y-axis-1",
                }]
              },
              options: {
                title:  {
                  display: true,
                  text: "今日の生産数"
                },
                scales: {
                  xAxes:[{
                    categoryPercentage: 1,
                  }],
                  yAxes: [{
                    id: "y-axis-1",
                    type: "linear",
                    position: "left",
                    scaleLabel: {
                      display: true,
                      labelString: "一時間当たりの生産数",
                      fontSize: 14,
                      fontColor: 'rgba(255, 99, 132, 1.0)'
                    },
                    ticks: {
                      beginAtZero:true,
                      stepSize: gon.per_case
                    }
                  },{
                    id: "y-axis-2",
                    type: "linear",
                    position: "right",
                    scaleLabel: {
                      display: true,
                      labelString: "累計生産数",
                      fontSize: 14,
                      fontColor: 'rgba(52, 147, 255, 1.0)'
                    },
                    ticks: {
                      beginAtZero:true
                    }
                  }]
                }
              }
            });